name: Build & Deploy

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy E-commerce application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

    dependency-submission:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Setup JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'

        - name: Generate and submit dependency graph
          uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
